[package]
name = "blocker_scheduler"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
blocker_core = { path = "../blocker_core" }
chrono = "0.4"
tokio = { version = "1", features = ["full"] }
ctrlc = "3.4"