[package]
name = "blocker_core"
version = "0.1.0"
edition = "2024"

[dependencies]
diesel = { version = "2.2.0", features = ["sqlite"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
directories = "5"
dotenvy = "0.15"
diesel_migrations = "2"